"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const webhook_1 = require("../controllers/webhook");
const middlewares_1 = require("../middlewares");
const WebhookSchema_1 = require("../schemas/WebhookSchema");
const WebhookRouter = (0, express_1.Router)();
WebhookRouter.post('/midtrans', middlewares_1.MiddleWares.validate({ body: WebhookSchema_1.midtransWebhookBodySchema }), webhook_1.WebhookController.midtransWebhookHandler);
WebhookRouter.post('/bitships', middlewares_1.MiddleWares.validate({ body: WebhookSchema_1.bitshipWebhookBodySchema }), webhook_1.WebhookController.bitshipWebhookHandler);
exports.default = WebhookRouter;
